version: '3'

services:
  web:
    build: .
    command: >
      bash -c "flask run -h 0.0.0.0"
    environment:
      - FLASK_APP=app:app
      - FLASK_ENV=development
    volumes:
      - ./store_locator:/app
    ports:
      - "5000:5000"
